services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_planner_db
    volumes:
      - event_planner_db_data:/var/lib/postgresql/data
    networks:
      - event-network

  #backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=event_planner_db;Username=user;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - event-network

  #frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  event_planner_db_data:
